- src/app/order/deliveryList/page.tsx
> request test

- src/app/order/deliveryAdd/page.tsx
- src/components/InputText/InputText.tsx
- 휴대폰 번호 유효성 검사 추가
- 자동 하이푼 할당 구현
-
> [featuer/TTAR-25]

- src/app/order/deliveryList/deliveryList.scss
- src/app/order/deliveryList/page.tsx
- src/components/Style/MainEventBtn/MainEventBtn.tsx
- "배송지 추가" 버튼 추가
- "수정" 버튼 경로 변경 router.push('/order/deliveryAdd') => router.push('/order/deliveryEdit')
- MainEventButton 스타일 수정
> [feat] 배송지추가 버튼 추가, 수정 버튼 경로 변경, MainEventButton 스타일 수정

- src/app/order/deliveryEdit/deliveryEdit.scss
- src/app/order/deliveryEdit/page.tsx
- src/app/order/deliveryList/deliveryList.scss
- src/app/order/deliveryList/page.tsx
- src/components/Style/MainEventBtn/MainEventBtn.tsx
> [feat] 배송지 수정 페이지 추가

- src/app/order/[deliveryId]/editDelivery/page.tsx
- src/app/order/newDelivery/page.tsx
- src/components/deliveryWrite/DeliveryWrite.scss
- src/components/deliveryWrite/DeliveryWrite.tsx
- 배송지 작성 컴포넌트화
- 배송지 수정, 배송지 추가 페이지에서 컴포넌트 불러와서 요소만 다르게 주도록 작성
-
> [feat] 배송지 작성 페이지 컴포넌트화 및 배송지 추가, 수정 페이지 작성

- src/app/order/deliveryList/page.tsx
> 페이지 경로 변경으로 인한 경로 수정

- src/app/review/page.tsx
- src/app/review/review.scss
> [style] 나의 리뷰 스타일 수정

- src/components/Checkbox/Checkbox.scss
- src/components/Checkbox/Checkbox.tsx
> [feat] checkbox 컴포넌트화

- public/downArrow.svg
- src/app/join/join.scss
- src/app/join/page.tsx
- src/app/login/page.tsx
- src/components/EmailAddress/EmailAddress.scss
- src/components/EmailAddress/EmailAddress.tsx
- src/components/InputText/InputText.scss
- src/components/InputText/InputText.tsx
- 회원가입 페이지 추가
- InputText 컴포넌트 수정
- EmailAddress 컴포넌트 추가
-
> [feat] 회원가입 페이지 완료, InputText 컴포넌트 수정, EmailAddress 컴포넌트 추가

- src/app/join/page.tsx
- src/app/order/deliveryList/page.tsx
- src/app/productsDetail/[params]/writeAsk/page.tsx
- src/app/user/page.tsx
- src/components/EmailAddress/EmailAddress.scss
- src/components/EmailAddress/EmailAddress.tsx
- src/components/InputText/InputText.scss
- src/components/InputText/InputText.tsx
- src/components/deliveryWrite/DeliveryWrite.scss
- src/components/deliveryWrite/DeliveryWrite.tsx
- InputText 컴포넌트 수정
- 비밀글, 기본배송지 CheckBox 컴포넌트로 수정
- 마이페이지 배송지관리 router.push 경로 변경
> [feat] InputText 컴포넌트 수정,비밀글, 기본배송지 CheckBox  컴포넌트로 수정

- src/app/findId/findId.scss
- src/app/findId/page.tsx
- src/app/findPassword/findPassword.scss
- src/app/findPassword/page.tsx
- src/app/join/page.tsx
- src/app/login/page.tsx
- src/app/order/deliveryList/page.tsx
- src/app/productsDetail/[params]/writeAsk/page.tsx
- src/app/user/page.tsx
- src/components/EmailAddress/EmailAddress.scss
- src/components/EmailAddress/EmailAddress.tsx
- src/components/Header/Header.scss
- src/components/InputText/InputText.scss
- src/components/InputText/InputText.tsx
- src/components/deliveryWrite/DeliveryWrite.scss
- src/components/deliveryWrite/DeliveryWrite.tsx
> [feature] 아이디/비밀번호 찾기 페이지 작성 및 연결

- src/components/EmailAddress/EmailAddress.scss
- 이메일 선택 DropDown 화살표 위치 수정, 모달 위치 수정
-
> [design] 이메일 선택 dropDown 화살표 위치 수정

- src/app/cart/cart.scss
> [style] 세미콜론 제거

- src/app/join/page.tsx
- src/util/AxiosGet.tsx
> [feat] 회원가입 api type 적용

- src/app/join/join.scss
- src/app/join/page.tsx
- src/components/EmailAddress/EmailAddress.tsx
- src/components/InputText/InputText.scss
- src/components/InputText/InputText.tsx
> [feat] 회원가입 폼 수정 및 post 작업

- src/app/join/page.tsx
- 로그인 성공 모달 추가
- 로그인 실패 모달 추가
- 각각 버튼 이벤트 추가
-
> [feat] 모달 버튼 이벤트 설정

- src/app/login/login.scss
- src/app/login/page.tsx
- src/types/user.ts
- src/util/AxiosGet.tsx
- 로그인 API 연결
- 로긍인 화면 남은 UI 작업 진행 중
-
> [feat] 로그인 API 연결, 로그인 화면 남은 UI 작업 진행중

- src/app/login/login.scss
- src/app/login/page.tsx
> [feat] 로그인 API 연결 완료

- src/app/user/page.tsx
- src/app/user/user.scss
- src/types/user.ts
- src/util/AxiosGet.tsx
- 프로필 이미지 업데이트 API 연결
- 로그인시 닉네임 설정
-
> [feat] 프로필 이미지 업데이트 API 연결

- src/types/user.ts
- src/util/AxiosGet.tsx
> [style] 인테페이스 타입 I 로 구분

- src/app/productsDetail/[params]/writeAsk/page.tsx
- src/components/Write/Write.tsx
- src/types/user.ts
- src/util/AxiosGet.tsx
> [feat] 문의하기 api 작성

- src/app/order/deliveryList/deliveryList.scss
- src/app/order/deliveryList/page.tsx
- src/components/Write/Write.tsx
- src/components/deliveryWrite/DeliveryWrite.tsx
- src/types/common.ts
- src/util/AxiosGet.tsx
- src/util/AxiosMember.tsx
- AxiosMemeber.ts 생성 후 배송지 CRUD 생성
- 배송지 조회, 추가, 삭제 구현
- 기본 배송지 삭제 시 오류 모달창 생성하여 에러 메세지 표시되도록 구현
- 업데이트는 아직 구현이 안 되어서 내일 작성해서 푸쉬하겠습니다!
> [feat] 배송지 조회, 추가, 삭제 구현

- src/app/order/[deliveryId]/editDelivery/page.tsx
- src/app/order/newDelivery/page.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/deliveryWrite/DeliveryWrite.tsx
- src/util/AxiosMember.tsx
> [feat] 배송지 수정 기능 구현

- next.config.js
- src/app/category/page.tsx
- src/app/products/[params]/page.tsx
- src/components/CategoryItem/Category.tsx
- src/components/Header/Header.tsx
- src/components/Item/ItemBox.tsx
- src/types/common.ts
- src/util/AxiosItem.tsx
> [feat] 카테고리 별 아이템

- src/app/products/[params]/page.tsx
- src/util/AxiosItem.tsx
> [feat] 카테고리 별 무한스크롤 구현

- src/app/heart/page.tsx
- src/components/ProductDetailAddInform/ProductDetailAddInform.tsx
- src/components/ProductDetailBuyInform/ProductDetailBuyInform.scss
- src/components/deliveryWrite/DeliveryWrite.tsx
> [feat] 찜 목록 API 연결

- src/app/main/page.tsx
- src/app/products/[params]/page.tsx
- src/app/search/[params]/page.tsx
- src/app/search/page.tsx
- src/components/CategoryItem/Category.tsx
- src/components/Item/ItemBox.tsx
- src/components/ProductDetailAddInform/ProductDetailAddInform.tsx
- src/util/AxiosItem.tsx
> [refactor] API 변경으로 인한 수정

- src/app/cart/page.tsx
- src/app/main/page.tsx
- src/app/productsDetail/[params]/page.tsx
- src/app/productsDetail/[params]/productsDetail.scss
- src/components/ProductDetailAddInform/ProductDetailAddInform.tsx
- src/components/ProductDetailBuyInform/ProductDetailBuyInform.tsx
- src/store/userInformation.tsx
- src/types/common.ts
- src/util/AxiosItem.tsx
- src/util/AxiosMember.tsx
> [feat] 장바구니 추가, 조회 API 연결

- src/app/category/page.tsx
- src/app/findId/page.tsx
- src/app/heart/page.tsx
- src/app/join/page.tsx
- src/app/order/page.tsx
- src/app/orderList/detail/page.tsx
- src/app/products/[params]/page.tsx
- src/app/successOrder/page.tsx
- src/components/EmailAddress/EmailAddress.scss
- src/components/EmailAddress/EmailAddress.tsx
- src/components/InputText/InputText.tsx
- src/components/Item/ItemBox.tsx
- src/components/ProductDetailAddInform/ProductDetailAddInform.scss
- src/components/ProductDetailAddInform/ProductDetailAddInform.tsx
- src/components/ProductDetailReview/ProductDetailReview.scss
- src/components/ProductDetailReview/ProductDetailReview.tsx
- src/components/Write/Write.scss
- src/components/Write/Write.tsx
- src/types/common.ts
- src/util/AxiosMember.tsx
- src/util/Axiosinquiry.tsx
- 문의하기, 찜목록, 아이디 찾기 이메일 인증, 결제 완료 페이지
-
> 문의하기, 찜목록, 아이디 찾기 이메일 인증, 결제 완료 페이지

- src/app/productsDetail/[itemId]/page.tsx
- src/components/ProductDetailAsk/ProductDetailAsk.tsx
- src/components/ReviewWrite/ReviewWrite.tsx
- src/util/AxiosReview.ts
- src/util/Axiosinquiry.tsx
> [feat] 문의 가져오기 리스트 가져오기 api 요청 구현, 문의 리스트 가져오기 구현

- src/app/findId/page.tsx
- src/app/main/page.tsx
- src/components/EmailAddress/EmailAddress.tsx
- src/util/AxiosMember.tsx
> [feat] 아이디 찾기 이메일 인증 진행 중
